repos:
-   repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: end-of-file-fixer
