trainer: forces

dataset:
  - src: /home/jovyan/shared-datasets/OC20/s2ef/2M/train
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /home/jovyan/shared-datasets/OC20/s2ef/all/val_id_30k

logger: wandb

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  #relax_dataset:
  #        src: /home/jovyan/shared-scratch/oc20_cleanup/mshuaibi/dft_is2rs/val_subset/single/data.lmdb
  write_pos: True
  relaxation_steps: 300
  relax_opt:
          maxstep: 0.04
          memory: 50
          damping: 1.0
          alpha: 70.0
          traj_dir: /home/jovyan/shared-scratch/oc20_cleanup/adeesh/test_delete

model:
  name: spinconv_grad11_uncertainty
  model_ref_number: 59
  hidden_channels: 32
  mid_hidden_channels: 256
  num_interactions: 3
  num_basis_functions: 512
  sphere_size_lat: 16
  sphere_size_long: 12
  max_num_neighbors: 40
  cutoff: 6.0
  sphere_message: fullconv
  output_message: fullconv
  force_estimator: random
  energy_estimator: mlpnode
  regress_forces: True
  use_pbc: True
  gaussian_learnable: False
  scale_distances: True
  basis_width_scalar: 3.0
  num_rand_rotations: 3
  otf_graph: True

optim:
  batch_size: 1
  eval_batch_size: 1
  num_workers: 4
  lr_initial: 0.0004
  optimizer: Adam
  optimizer_params: {"amsgrad": True}
  eval_every: 5000
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 10 # 80
  force_coefficient: 100
  energy_coefficient: 1
