name: Test

env:
  OMP_NUM_THREADS: '1'

on: [push, pull_request]

jobs:
  light_test:
    name: Test

    runs-on: [self-hosted, linux, shared-scratch]

    container:
      image: docker://ulissigroup/kubeflow_vasp:amptorch_ocp
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout actions
      uses: actions/checkout@v2
    - name: Set up environment
      run: |
        export CWD=$(pwd)
        cd $CWD
    - name: Run pytest on light test suite unit tests
      run: |
        pytest finetuna/tests/suites/light_suite.py -s
