name: Test al_mlp by running unit tests with pytest

env:
  OMP_NUM_THREADS: '1'

on: [push, pull_request]

jobs:
  test_local_scheduler:
    name: Test al_mlp with light test suite

    runs-on: [self-hosted, linux, shared-scratch]

    container:
      image: docker://ulissigroup/kubeflow_vasp:amptorch_ocp

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run pytest on light test suite unit tests
      uses: actions/checkout@v2
      run: |
        pip install git+https://github.com/uncertainty-toolbox/uncertainty-toolbox
        cd /home/jovyan
        git clone https://github.com/ulissigroup/amptorch
        cd /home/jovyan/amptorch
        python setup.py install
        git clone https://github.com/Open-Catalyst-Project/ocp
        cd /home/jovyan/ocp
        pip install -e .
        pytest al_mlp/tests/suites/light_suite.py